In [ ]:
Imputing missing values through various strategies

In [2]:
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
iris_X = iris.data

In [3]:
masking_array = np.random.binomial(1, .25,iris_X.shape).astype(bool)
iris_X[masking_array] = np.nan

In [4]:
masking_array[:5]

array([[ True, False, False, False],
       [ True, False, False,  True],
       [False, False,  True,  True],
       [ True, False,  True, False],
       [ True, False,  True, False]], dtype=bool)

In [5]:
iris_X [:5]

array([[ nan,  3.5,  1.4,  0.2],
       [ nan,  3. ,  1.4,  nan],
       [ 4.7,  3.2,  nan,  nan],
       [ nan,  3.1,  nan,  0.2],
       [ nan,  3.6,  nan,  0.2]])

In [6]:
from sklearn import preprocessing
impute = preprocessing.Imputer()
iris_X_prime = impute.fit_transform(iris_X)
iris_X_prime[:5]

array([[ 5.86371681,  3.5       ,  1.4       ,  0.2       ],
       [ 5.86371681,  3.        ,  1.4       ,  1.2619469 ],
       [ 4.7       ,  3.2       ,  3.78918919,  1.2619469 ],
       [ 5.86371681,  3.1       ,  3.78918919,  0.2       ],
       [ 5.86371681,  3.6       ,  3.78918919,  0.2       ]])

In [7]:
iris_X_prime[0, 0]

5.8637168141592939

In [8]:
iris_X[0, 0] 

nan

In [9]:
impute = preprocessing.Imputer(strategy='median')
iris_X_prime = impute.fit_transform(iris_X)
iris_X_prime[:5]

array([[ 5.8,  3.5,  1.4,  0.2],
       [ 5.8,  3. ,  1.4,  1.4],
       [ 4.7,  3.2,  4.2,  1.4],
       [ 5.8,  3.1,  4.2,  0.2],
       [ 5.8,  3.6,  4.2,  0.2]])

In [10]:
iris_X[np.isnan(iris_X)] = -1
iris_X[:5]

array([[-1. ,  3.5,  1.4,  0.2],
       [-1. ,  3. ,  1.4, -1. ],
       [ 4.7,  3.2, -1. , -1. ],
       [-1. ,  3.1, -1. ,  0.2],
       [-1. ,  3.6, -1. ,  0.2]])

In [11]:
impute = preprocessing.Imputer(missing_values=-1)
iris_X_prime = impute.fit_transform(iris_X)
iris_X_prime[:5]

array([[ 5.86371681,  3.5       ,  1.4       ,  0.2       ],
       [ 5.86371681,  3.        ,  1.4       ,  1.2619469 ],
       [ 4.7       ,  3.2       ,  3.78918919,  1.2619469 ],
       [ 5.86371681,  3.1       ,  3.78918919,  0.2       ],
       [ 5.86371681,  3.6       ,  3.78918919,  0.2       ]])

In [12]:
import pandas as pd
iris_X_prime = np.where(pd.DataFrame(iris_X).isnull(),-1,iris_X)
iris_X_prime[:5]

array([[-1. ,  3.5,  1.4,  0.2],
       [-1. ,  3. ,  1.4, -1. ],
       [ 4.7,  3.2, -1. , -1. ],
       [-1. ,  3.1, -1. ,  0.2],
       [-1. ,  3.6, -1. ,  0.2]])

In [13]:
pd.DataFrame(iris_X).fillna(-1)[:5].values

array([[-1. ,  3.5,  1.4,  0.2],
       [-1. ,  3. ,  1.4, -1. ],
       [ 4.7,  3.2, -1. , -1. ],
       [-1. ,  3.1, -1. ,  0.2],
       [-1. ,  3.6, -1. ,  0.2]])