In [ ]:
Putting it all together with Pipelines

In [1]:
from sklearn.datasets import load_iris
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris()
iris_data = iris.data
mask = np.random.binomial(1, .25, iris_data.shape).astype(bool)
iris_data[mask] = np.nan
iris_data[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  nan,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  nan,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [2]:
from sklearn import pipeline, preprocessing, decomposition


pca = decomposition.PCA()
imputer = preprocessing.Imputer()


pipe = pipeline.Pipeline([('imputer', imputer), ('pca', pca)])
iris_data_transformed = pipe.fit_transform(iris_data)
iris_data_transformed[:5]

array([[-2.60698767, -0.08712965,  0.24363406,  0.22537488],
       [-0.62326808,  1.07071559,  0.59357313,  0.00601078],
       [-2.80094824,  0.27826148,  0.01939741,  0.02894031],
       [-0.72165678,  1.30496332,  0.51085746,  0.17514322],
       [-2.64378029, -0.02318272,  0.23004317,  0.34525975]])

In [3]:
pipe2 = pipeline.make_pipeline(imputer, pca)
pipe2.steps

[('imputer',
  Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)),
 ('pca',
  PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False))]

In [4]:
iris_data_transformed2 = pipe2.fit_transform(iris_data)
iris_data_transformed2[:5]

array([[-2.60698767, -0.08712965,  0.24363406,  0.22537488],
       [-0.62326808,  1.07071559,  0.59357313,  0.00601078],
       [-2.80094824,  0.27826148,  0.01939741,  0.02894031],
       [-0.72165678,  1.30496332,  0.51085746,  0.17514322],
       [-2.64378029, -0.02318272,  0.23004317,  0.34525975]])

In [5]:
pipe2.set_params(pca__n_components=2)

Pipeline(memory=None,
     steps=[('imputer', Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)), ('pca', PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False))])

In [6]:
iris_data_transformed3 = pipe2.fit_transform(iris_data)
iris_data_transformed3[:5]

array([[-2.60698767, -0.08712965],
       [-0.62326808,  1.07071559],
       [-2.80094824,  0.27826148],
       [-0.72165678,  1.30496332],
       [-2.64378029, -0.02318272]])