In [ ]:
Numpy Basics

In [1]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
array_1 = np.arange(10)
array_1.shape

(10L,)

In [3]:
array_1.ndim      #Find number of dimensions of array_1

1

In [4]:
array_1.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
array_1 = array_1.reshape((5,2))
array_1.ndim

2

In [7]:
array_1 + 1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
array_2 = np.arange(10)
array_2 * array_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
array_2 = array_2 ** 2  #Note that this is equivalent to array_2 * array_2
array_2 = array_2.reshape((5,2))
array_2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [10]:
array_1 = array_1 + 1
array_1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
array_1 + array_2

array([[ 1,  3],
       [ 7, 13],
       [21, 31],
       [43, 57],
       [73, 91]])

In [12]:
np.zeros((5,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [14]:
np.ones((5,2), dtype = np.int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [13]:
np.empty((5,2), dtype = np.float)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [15]:
array_1[0,0]   #Finds value in first row and first column.

1

In [16]:
array_1[0,:]

array([1, 2])

In [17]:
array_1[:,0]

array([1, 3, 5, 7, 9])

In [18]:
array_1[2:5, :]

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
array_1[2:5,0]

array([5, 7, 9])

In [20]:
array_1 > 5

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [21]:
array_1[array_1 > 5]

array([ 6,  7,  8,  9, 10])

In [22]:
array_1.sum()

55

In [23]:
array_1.sum(axis = 1)

array([ 3,  7, 11, 15, 19])

In [24]:
array_1.sum(axis = 0)

array([25, 30])

In [25]:
array_1.mean(axis = 0)

array([ 5.,  6.])

In [27]:
array_3 = np.array([np.nan, 0, 1, 2, np.nan])
np.isnan(array_3)

array([ True, False, False, False,  True], dtype=bool)

In [28]:
array_3[~np.isnan(array_3)]

array([ 0.,  1.,  2.])

In [29]:
array_3[np.isnan(array_3)] = 0
array_3

array([ 0.,  0.,  1.,  2.,  0.])