In [ ]:
K-fold cross validation

In [2]:
import numpy as np
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8],[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 1, 2, 1, 2, 1, 2])

In [5]:
from sklearn.model_selection import KFold

kf= KFold(n_splits = 4)

cc = 1
for train_index, test_index in kf.split(X):
    print "Round : ",cc,": ",
    print "Training indices :", train_index,
    print "Testing indices :", test_index
    cc += 1

Round :  1 :  Training indices : [2 3 4 5 6 7] Testing indices : [0 1]
Round :  2 :  Training indices : [0 1 4 5 6 7] Testing indices : [2 3]
Round :  3 :  Training indices : [0 1 2 3 6 7] Testing indices : [4 5]
Round :  4 :  Training indices : [0 1 2 3 4 5] Testing indices : [6 7]


In [6]:
kf.get_n_splits()

4

In [7]:
indices_list = list(kf.split(X))

In [8]:
indices_list[3] #the list is indexed from 0 to 3

(array([0, 1, 2, 3, 4, 5], dtype=int64), array([6, 7], dtype=int64))

In [9]:
train_indices, test_indices = indices_list[3]
X[train_indices]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [10]:
y[train_indices]

array([1, 2, 1, 2, 1, 2])

In [11]:
X[test_indices]

array([[5, 6],
       [7, 8]])