In [ ]:
Using truncated SVD to reduce dimensionality

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
iris_X = iris.data
y = iris.target

In [2]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(2)
iris_transformed = svd.fit_transform(iris_X)

In [3]:
svd.explained_variance_ratio_

array([ 0.53028106,  0.44685765])

In [6]:
from scipy.linalg import svd
import numpy as np
D = np.array([[1, 2], [1, 3], [1, 4]])
D

array([[1, 2],
       [1, 3],
       [1, 4]])

In [7]:
U, S, V = svd(D, full_matrices=False)
U.shape, S.shape, V.shape

((3L, 2L), (2L,), (2L, 2L))

In [8]:
np.dot(U.dot(np.diag(S)), V)

array([[ 1.,  2.],
       [ 1.,  3.],
       [ 1.,  4.]])

In [10]:
new_S = S[0]
new_U = U[:, 0]
new_U.dot(new_S)


tsvd = TruncatedSVD(2)
tsvd.fit(iris_X)
tsvd.transform(iris_X)

array([[  5.91220352e+00,   2.30344211e+00],
       [  5.57207573e+00,   1.97383104e+00],
       [  5.44648470e+00,   2.09653267e+00],
       [  5.43601924e+00,   1.87168085e+00],
       [  5.87506555e+00,   2.32934799e+00],
       [  6.47699043e+00,   2.32552598e+00],
       [  5.51542859e+00,   2.07156181e+00],
       [  5.85042297e+00,   2.14948016e+00],
       [  5.15851287e+00,   1.77642658e+00],
       [  5.64458172e+00,   1.99190598e+00],
       [  6.26482670e+00,   2.42727947e+00],
       [  5.75150446e+00,   2.02142409e+00],
       [  5.48017099e+00,   1.97972378e+00],
       [  4.95064168e+00,   2.04947793e+00],
       [  6.52528515e+00,   2.91774840e+00],
       [  6.78960484e+00,   2.82549990e+00],
       [  6.27173006e+00,   2.60908548e+00],
       [  5.92899145e+00,   2.26896626e+00],
       [  6.64757408e+00,   2.39126214e+00],
       [  6.09424306e+00,   2.36154331e+00],
       [  6.25352038e+00,   2.12203279e+00],
       [  6.07305216e+00,   2.27257849e+00],
       [  